name: upath
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.10
    - fsspec
    # optional
    - requests
    - s3fs
    - jupyter
    - ipython
    - pytest
    - pylint
    - flake8
    - pyarrow
    - moto
    - pip
    - pip:
      - hadoop-test-cluster
      - gcsfs
      - nox
